In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
company = pd.read_csv("C:\\Data science\\Data sets\\Decision Tree\\Company_Data.csv")
company.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [3]:
company["dummy"] = pd.factorize(company.ShelveLoc)[0]
company["dummy1"] = pd.factorize(company.Urban)[0]
company["dummy2"] = pd.factorize(company.US)[0]
Drp = company.drop(["ShelveLoc","Urban","US"],axis = 1)
comp = Drp.rename(columns = {"dummy":"ShelveLoc","dummy1":"Urban","dummy2":"US"})
comp.head()

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0   9.50        138      73           11         276    120   42         17   
1  11.22        111      48           16         260     83   65         10   
2  10.06        113      35           10         269     80   59         12   
3   7.40        117     100            4         466     97   55         14   
4   4.15        141      64            3         340    128   38         13   

   ShelveLoc  Urban  US  
0          0      0   0  
1          1      0   0  
2          2      0   0  
3          2      0   0  
4          0      0   1

In [14]:
comp["Sales"] = comp.Sales.astype("category")
comp.dtypes

Sales          category
CompPrice         int64
Income            int64
Advertising       int64
Population        int64
Price             int64
Age               int64
Education         int64
ShelveLoc         int64
Urban             int64
US                int64
dtype: object

In [46]:
from sklearn import preprocessing
sal= comp.Sales
le = preprocessing.LabelEncoder()
target = le.fit_transform(sal)
inputs  = comp.drop(["Sales"],axis = 1)
target

array([255, 297, 267, 158,  37, 290, 133, 306, 129,  55, 234, 309,  33,
       291, 294, 219, 170, 315, 331, 220, 122, 314,  71, 103, 271, 333,
       203,  77,  16, 184, 330, 200, 117, 223,  13, 293, 230,  63, 131,
        21,   8, 189, 277,  36,  38,  51, 317,  45,  32, 284,   5,  46,
       187, 145,  61, 140, 307,   4,  86,  75, 202, 154,   6, 208, 183,
        61, 227, 234, 328, 190, 252, 126,  88, 321, 117, 210, 286, 177,
        47, 239, 191, 165, 302,  46,   9, 208, 218, 304, 130, 188,  82,
        58,  49, 228, 204,  93, 253, 162, 318,  60,  35, 117,  79,  70,
        52,  90,   1, 210,  24, 232, 233, 132, 135, 110, 242, 209,  71,
       226, 169, 156, 141, 303, 142, 196, 229, 245, 298, 127,  64,  48,
       205, 126, 257, 172,  28, 125,  74, 127, 274, 316, 111, 128, 161,
         3, 237, 223,  31, 282, 168, 300, 280, 289, 174, 105, 143, 178,
       163, 272, 319, 243,  53,  15,  27,  96, 198,   2, 137, 137, 153,
       300, 191, 318, 235, 120,   0, 167,  94, 279, 287, 182,  6

In [37]:
x_train,x_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)
len(x_test)

80

In [33]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=15,criterion="entropy")
model.fit(x_train,y_train)

C:\Users\Kamal\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\Kamal\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=2,
                       oob_score=True)

In [48]:
pred = model.predict(x_test)
pred

array([ 84, 155, 117, 301,  68,  51, 223,  43,  59, 309,  32,  55, 201,
       217, 184, 120,  63, 127,  79, 121,  61,  57, 205,  34, 139,  49,
       236, 252,  52,  52, 220,  71, 142,  65, 269, 171, 253, 265, 205,
       290,  48, 312, 170, 276, 295,  30, 335, 282, 168,   5, 151,  30,
       142,  62, 162,  79,  95, 163, 280,  49,  15, 130, 310,  36,  70,
       180, 328,   9, 146, 326,  62, 292, 195,  41, 227, 177, 322, 242,
       102, 273], dtype=int64)

In [41]:
model.score(x_test,y_test)

0.75

In [42]:
y_test

array([137, 155, 117, 301,  68,  51, 223,  43, 133, 309,  32,  55, 201,
       217, 184, 120,  63, 191, 111, 147,  61,  57, 205,  34, 139, 315,
       236, 252,  27, 152, 220,  71,  60,  65, 269, 171, 122, 265, 173,
       290,  48, 312, 170, 276, 295,  97, 335, 282, 168, 106, 151,  39,
       142,  29, 320,  89,  95, 163, 280,  49,  15, 130, 310,  36,  70,
       180, 328,   9, 146, 326,  62, 292, 178,  41, 227,  35, 319, 242,
       102, 273], dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [52]:
fraud = pd.read_csv("C:\\Data science\\Data sets\\Decision Tree\\Fraud_check.csv")
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [53]:
fraud["Target"] = ["Risky" if x <= 30000  else "Good" for x in fraud['Taxable.Income']] 
fraud.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban Target  
0   YES   Good  
1   YES   Good  
2   YES   Good  
3   YES   Good  
4    NO   Good

In [54]:
fraud["dummy_Target"] = pd.factorize(fraud.Target)[0]
fraud["dummy_Mar"] = pd.factorize(fraud['Marital.Status'])[0]
fraud["dummy_Un"] = pd.factorize(fraud['Undergrad'])[0]
fraud["dummy_ur"] = pd.factorize(fraud['Urban'])[0]
drp = fraud.drop(["Marital.Status","Undergrad","Urban"],axis = "columns")
FRD = drp.rename(columns = {"dummy_Mar":"Marital.Status","dummy_Un":"Undergrad","dummy_ur":"Urban"})
FRD.head()

Taxable.Income  City.Population  Work.Experience Target  dummy_Target  \
0           68833            50047               10   Good             0   
1           33700           134075               18   Good             0   
2           36925           160205               30   Good             0   
3           50190           193264               15   Good             0   
4           81002            27533               28   Good             0   

   Marital.Status  Undergrad  Urban  
0               0          0      0  
1               1          1      0  
2               2          0      0  
3               0          1      0  
4               2          0      1

In [55]:
target1 = FRD.Target
inputs1 = FRD.drop(["Target","dummy_Target"],axis = "columns")

In [56]:
X_train,X_test,Y_train,Y_test = train_test_split(inputs1,target1,test_size = 0.2)

In [57]:
#len(X_train)
len(X_test)

120

In [58]:
model1 = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=15,criterion="entropy")
model1.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=2,
                       oob_score=True)

In [61]:
Y_test

595     Good
1       Good
303     Good
597     Good
24      Good
       ...  
134     Good
259    Risky
132     Good
76      Good
576     Good
Name: Target, Length: 120, dtype: object

In [63]:
preds = model1.predict(X_test)
preds

array(['Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Risky', 'Risky', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Risky', 'Risky', 'Good', 'Good', 'Good',
       'Risky', 'Good', 'Risky', 'Risky', 'Good', 'Good', 'Risky',
       'Risky', 'Good', 'Good', 'Risky', 'Risky', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Risky',
       'Good', 'Good', 'Risky', 'Good', 'Good', 'Risky', 'Risky', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Risky', 'Good',
       'Risky', 'Risky', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Risky', 'Good', 'Good', 'Risky',
       'Risky', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Risky', 

In [64]:
confusion_matrix(Y_test,preds)

array([[97,  0],
       [ 0, 23]], dtype=int64)

In [65]:
print("Accuracy",(97+23)/(97+0+0+23)) # 100 percentage accuracy

Accuracy 1.0
