In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [2]:
test = pd.read_csv("C:\\Data science\\Data sets\\Naive Bayes\\SalaryData_Test.csv")
test.head()

Age   Workclass      Education  Educationno        Maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           Occupation    Relationship    Race    Sex  Capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   Capitalloss  Hoursperweek          Native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [6]:
test.drop(["Age","Education"],axis="columns")
test.head()

KeyError: "['Age' 'Education'] not found in axis"

In [8]:
test["dummy"]=pd.factorize(test.Workclass)[0]
test["dummy1"]=pd.factorize(test.Maritalstatus)[0]
test["dummy2"]=pd.factorize(test.Occupation)[0]
test["dummy3"]=pd.factorize(test.Relationship)[0]
test["dummy4"]=pd.factorize(test.Sex)[0]
test["dummy5"]=pd.factorize(test.Native)[0]
test["dummy6"]=pd.factorize(test.Salary)[0]
test["dummy7"]=pd.factorize(test.Race)[0]
test1=test.drop(["Workclass","Maritalstatus","Occupation","Relationship","Race","Sex","Native","Salary"],axis=1)
test2=test1.rename(columns={"dummy":"Workclass","dummy1":"Maritalstatus","dummy2":"Occupation","dummy3":"Relationship",
                    "dummy4":"Sex","dummy5":"Native","dummy6":"Salary","dummy7":"Race"})

In [9]:
test2.head()

Educationno  Capitalgain  Capitalloss  Hoursperweek  Workclass  \
0            7            0            0            40          0   
1            9            0            0            50          0   
2           12            0            0            40          1   
3           10         7688            0            40          0   
4            6            0            0            30          0   

   Maritalstatus  Occupation  Relationship  Sex  Native  Salary  Race  
0              0           0             0    0       0       0     0  
1              1           1             1    0       0       0     1  
2              1           2             1    0       0       1     1  
3              1           0             1    0       0       1     0  
4              0           3             2    0       0       0     1

In [10]:


def dnorm(i):
    x = (i-i.min())/i.max()-i.min()
    return(x)
norm_data = dnorm(test2.iloc[:,:])

norm_data

Educationno  Capitalgain  Capitalloss  Hoursperweek  Workclass  \
0          -0.6250     0.000000          0.0     -0.606061   0.000000   
1          -0.5000     0.000000          0.0     -0.505051   0.000000   
2          -0.3125     0.000000          0.0     -0.606061   0.166667   
3          -0.4375     0.076881          0.0     -0.606061   0.000000   
4          -0.6875     0.000000          0.0     -0.707071   0.000000   
...            ...          ...          ...           ...        ...   
15055      -0.2500     0.000000          0.0     -0.606061   0.000000   
15056      -0.2500     0.000000          0.0     -0.646465   0.000000   
15057      -0.2500     0.000000          0.0     -0.505051   0.000000   
15058      -0.2500     0.054551          0.0     -0.606061   0.000000   
15059      -0.2500     0.000000          0.0     -0.404040   0.833333   

       Maritalstatus  Occupation  Relationship  Sex  Native  Salary  Race  
0           0.000000    0.000000           0.0  0.0     0.0     0.0  0.00  
1           0.166667    0.076923           0.2  0.0     0.0     0.0  0.25  
2           0.166667    0.153846           0.2  0.0     0.0     1.0  0.25  
3           0.166667    0.000000           0.2  0.0     0.0     1.0  0.00  
4           0.000000    0.230769           0.4  0.0     0.0     0.0  0.25  
...              ...         ...           ...  ...     ...     ...   ...  
15055       0.000000    0.307692           0.0  0.0     0.0     0.0  0.25  
15056       0.666667    0.307692           0.4  1.0     0.0     0.0  0.25  
15057       0.166667    0.307692           0.2  0.0     0.0     0.0  0.25  
15058       0.666667    0.461538           0.0  0.0     0.0     0.0  1.00  
15059       0.166667    0.538462           0.2  0.0     0.0     1.0  0.25  

[15060 rows x 12 columns]

In [11]:
target=norm_data.Salary
inputs=norm_data.drop(["Salary"],axis="columns")

In [12]:
#no NA values
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [14]:
len(x_train)
#len(x_test)

12048

In [15]:
len(inputs)

15060

In [16]:
#Naive  Bayes model
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [45]:
model.score(x_test,y_test)

0.8031208499335989

In [46]:
x_test[:10]

Educationno  Capitalgain  Capitalloss  Hoursperweek  Workclass  \
5954       -0.4375     0.000000          0.0     -0.505051   0.333333   
1867       -0.6250     0.000000          0.0     -0.444444   0.000000   
5649       -0.3750     0.000000          0.0     -0.606061   0.000000   
1637       -0.7500     0.000000          0.0     -0.606061   0.000000   
12479      -0.4375     0.000000          0.0     -0.606061   0.166667   
9755       -0.5000     0.000000          0.0     -0.555556   0.000000   
477        -0.2500     0.000000          0.0     -0.606061   0.000000   
4862       -0.2500     0.072981          0.0     -0.606061   0.000000   
12248      -0.3750     0.000000          0.0     -0.606061   0.000000   
1926       -0.5000     0.000000          0.0     -0.404040   0.333333   

       Maritalstatus  Occupation  Relationship  Sex  Native  Race  
5954        0.000000    0.230769           0.4  0.0     0.0  0.25  
1867        0.166667    0.000000           0.2  0.0     0.0  0.00  
5649        0.166667    0.307692           0.2  0.0     0.0  0.25  
1637        0.000000    0.230769           0.0  1.0     0.0  0.25  
12479       0.666667    0.384615           0.4  0.0     0.0  0.25  
9755        0.166667    0.846154           0.2  0.0     0.0  0.25  
477         0.000000    0.538462           0.4  1.0     0.0  0.25  
4862        0.166667    0.538462           0.2  0.0     0.0  0.25  
12248       0.166667    0.461538           0.8  1.0     0.0  0.25  
1926        0.166667    0.538462           0.2  0.0     0.0  0.25

In [47]:
y_test[:10]

5954     0.0
1867     0.0
5649     0.0
1637     0.0
12479    0.0
9755     1.0
477      0.0
4862     1.0
12248    0.0
1926     1.0
Name: Salary, dtype: float64

In [48]:
model.predict(x_test[:10])

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [49]:
model_pred =model.predict(x_test)
model_pred


array([0., 0., 0., ..., 0., 0., 0.])

In [51]:
modelprob = model.predict_proba(x_test[:10])
modelprob

array([[9.77273293e-01, 2.27267071e-02],
       [9.96099745e-01, 3.90025502e-03],
       [9.70694306e-01, 2.93056937e-02],
       [9.99860697e-01, 1.39302973e-04],
       [9.99540106e-01, 4.59893643e-04],
       [9.87130769e-01, 1.28692314e-02],
       [9.96467305e-01, 3.53269546e-03],
       [3.57399803e-12, 1.00000000e+00],
       [9.99388408e-01, 6.11591937e-04],
       [9.37112199e-01, 6.28878010e-02]])

In [52]:
my_tab = pd.crosstab(index= model_pred,columns=y_test)
my_tab

Salary   0.0  1.0
row_0            
0.0     2147  464
1.0      129  272